"""Export the public command schema without starting DB/runtime or loading local config."""
import json
from pathlib import Path
from fastapi.openapi.utils import get_openapi


def describe(app, settings):
    from app.persistence.models import PHASES
    schema = get_openapi(title=app.title, version=app.version, routes=app.routes)
    schema["components"]["schemas"]["Phase"] = {"type": "string", "enum": list(PHASES)}
    schema["servers"] = [{"url": f"http://127.0.0.1:{settings.port}"}]
    schema["components"]["securitySchemes"] = {
        "localSession": {"type": "apiKey", "in": "cookie", "name": settings.cookie},
        "csrf": {"type": "apiKey", "in": "header", "name": "X-CSRF-Token"},
        "runtimeLease": {"type": "http", "scheme": "bearer", "description": "Trusted supervisor-issued job/owner/generation credential"},
    }
    error = {"description": "Structured command error",
        "content": {"application/json": {"schema": {"type": "object", "required": ["error"],
            "properties": {"error": {"type": "object", "required": ["code", "message", "details"],
                "properties": {"code": {"type": "string"}, "message": {"type": "string"},
                               "details": {"type": "object"}}}}}}}}
    for path, methods in schema["paths"].items():
        for method, operation in methods.items():
            public = path in ("/health", "/auth/login")
            runtime = path.startswith("/runtime/")
            operation["security"] = ([] if public else [{"runtimeLease": []}] if runtime else
                [{"localSession": [], **({"csrf": []} if method == "post" else {})}])
            if method == "post" and path not in ("/auth/login", "/auth/logout"):
                operation.setdefault("parameters", []).append({"in": "header", "name": "Idempotency-Key", "required": True,
                    "schema": {"type": "string", "minLength": 1, "maxLength": 160},
                    "description": "One stable key per logical command; reuse with changed work returns 409"})
            for code in ("401", "403", "404", "409", "422", "500"):
                operation["responses"][code] = error
            if path.endswith("/events"):
                operation.setdefault("parameters", []).append({"in": "header", "name": "Last-Event-ID", "required": False,
                    "schema": {"type": "string", "pattern": "^[0-9]{1,18}$"}, "description": "Persistent cursor; takes precedence over cursor query on native reconnect"})
                operation["responses"]["200"] = {"description": "SSE state, snapshot_required, session_expired; state id is persistent event cursor",
                    "content": {"text/event-stream": {"schema": {"type": "string"}}}}
    schema["x-public-response-types"] = "contracts/api/types.ts"
    return schema


def main():
    from .application import create_app
    app = create_app()
    target = Path(__file__).resolve().parents[4] / "contracts" / "api" / "openapi.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    schema = app.openapi()
    target.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    target.with_name("requests.ts").write_text(typescript(schema), encoding="utf-8")
    print("Exported contracts/api/openapi.json and requests.ts")


def typescript(schema):
    def render(value):
        if "$ref" in value: return value["$ref"].split("/")[-1]
        if "enum" in value: return " | ".join(json.dumps(x) for x in value["enum"])
        for key, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
            if key in value: return separator.join(render(x) for x in value[key])
        kind = value.get("type")
        if kind == "array": return f"({render(value.get('items', {}))})[]"
        if kind == "object":
            props = value.get("properties", {})
            required = value.get("required", [])
            parts = [f"{json.dumps(k)}{'' if k in required else '?'}: {render(v)};" for k, v in props.items()]
            extra = value.get("additionalProperties", not props)
            if extra: parts.append(f"[key: string]: {render(extra) if isinstance(extra, dict) else 'unknown'};")
            return "{ " + " ".join(parts) + " }"
        return {"integer": "number", "number": "number", "boolean": "boolean", "string": "string", "null": "null"}.get(kind, "unknown")
    lines = ["// Generated by python -m app.http.contract. Do not edit."]
    for name, definition in sorted(schema["components"]["schemas"].items()):
        lines.append(f"export type {name} = {render(definition)};")
    lines.append("export interface RequestBodies {")
    for path, methods in sorted(schema["paths"].items()):
        for method, operation in methods.items():
            content = operation.get("requestBody", {}).get("content", {}).get("application/json")
            if content: lines.append(f"  {json.dumps(method.upper() + ' ' + path)}: {render(content['schema'])};")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__": main()
